# kubectl create -f <root>/kube/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: localhost.localstack.cloud:4510/kube-poc:latest
          resources:
            requests:
              cpu: "1000m"
          startupProbe:
            httpGet:
              path: /
              port: 9999
            failureThreshold: 10
            periodSeconds: 6
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            failureThreshold: 1
            periodSeconds: 10
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 9999
            failureThreshold: 1
            periodSeconds: 10
          ports:
            - containerPort: 9999
#      imagePullSecrets:
#        - name: ecr-credential
      restartPolicy: Always
