# kubectl create -f <root>/kube/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: web-port
      port: 9999
      nodePort: 32635
